version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      # MONGO_INITDB_DATABASE: shop
    ports:
      - 27017:27017
    volumes:
      - ./init-database.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:1234@mongo:27017/
